name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deno install
        run: deno install

      - name: NPM install
        run: npm install

      # - name: Lint
      #   run: deno lint

      - name: Run tests
        run: deno task test

      # - name: Typedoc
      #   run: deno task typedoc || true

      - name: Typedoc
        run: ./node_modules/typedoc/bin/typedoc

      - name: Build
        run: deno task build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Setup NPM
      #   run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /home/runner/.npmrc
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Run release script
      #   run: /home/runner/.deno/bin/deno task release
