name: Prelude CI/CD

on:
  push:
    branches:
      - main
      - release

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      # - name: Lint
      #   run: deno lint
      - run: deno task test
  publish-jsr:
    needs: test
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno publish --allow-slow-types --allow-dirty
  publish-npm:
    needs: test
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Moving artifacts, website and docs into their own project...
      # - name: Setup Pages
        # uses: actions/configure-pages@v5

      # - name: Upload artifact
        # uses: actions/upload-pages-artifact@v3
        # with:
          # path: './www/dist'

      # - name: Deploy to GitHub Pages
        # id: deployment
        # uses: actions/deploy-pages@v4
